# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registrar_id', models.PositiveIntegerField(unique=True)),
                ('distribution_area', models.CharField(db_index=True, max_length=3, null=True)),
                ('department', models.CharField(db_index=True, max_length=3)),
                ('number', models.PositiveSmallIntegerField(db_index=True)),
                ('letter', models.CharField(default='', max_length=1)),
                ('pdf_allowed', models.BooleanField(db_index=True, default=True)),
                ('audit_allowed', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar_guid', models.PositiveIntegerField(db_index=True, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CrossListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=3)),
                ('number', models.PositiveSmallIntegerField(db_index=True)),
                ('letter', models.CharField(default='', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('employee_id', models.CharField(db_index=True, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.PositiveSmallIntegerField(choices=[(1, 'Fall'), (2, 'Spring')], db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('term', 'year')]),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='instructor',
            field=models.ManyToManyField(to='courses.Instructor'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('department', 'number', 'letter')]),
        ),
        migrations.AlterUniqueTogether(
            name='crosslisting',
            unique_together=set([('course', 'department', 'number', 'letter')]),
        ),
    ]
