# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='location',
            name='building',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.AddField(
            model_name='meeting',
            name='building',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
