# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180402_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')]),
        ),
    ]
